from pathlib import Path


"""
from configs.paths import PATH

"""


class PATH:

    PROJECT_ROOT = Path(__file__).parent.parent

    #================= original dataset =====================
    DATA_ROOT = PROJECT_ROOT.parent / "Data"

    DATASET_ABAW10th = DATA_ROOT / "Dataset_ABAW10th"
    DATASET_AffectNet = DATA_ROOT / "Dataset_AffectNet"
    DATASET_RAF = DATA_ROOT / "Dataset_RAF"

    #/* DATASET_ABAW10th */
    EXPR_TRAIN_ABAW10th = DATASET_ABAW10th / "annotations" / 'EXPR_Recognition_Challenge' / "Train_Set"
    EXPR_VALID_ABAW10th = DATASET_ABAW10th / "annotations" / 'EXPR_Recognition_Challenge' / "Validation_Set"
    VIDEO_batch1_ABAW10th = DATASET_ABAW10th / "videos" / "batch1"
    VIDEO_batch2_ABAW10th = DATASET_ABAW10th / "videos" / "batch2"
    VIDEO_batch3_ABAW10th = DATASET_ABAW10th / "videos" / "batch3"
    IMG_batch1_ABAW10th = DATASET_ABAW10th / "images" / "batch1"
    IMG_batch2_ABAW10th = DATASET_ABAW10th / "images" / "batch2"

    # /* DATASET_AffectNet */
    IMG_AffectNet = DATASET_AffectNet / "Manually_Annotated_Images"
    train_csv_AffectNet = DATASET_AffectNet / 'Manually_Annotated_file_lists' / 'training.csv'
    valid_csv_AffectNet = DATASET_AffectNet / 'Manually_Annotated_file_lists' / 'validation.csv'

    # /* DATASET_RAF */
    RAF_TRAIN = DATASET_RAF / 'train'
    RAF_VALID = DATASET_RAF / 'valid'

    # ================= created dataset =====================
    Dataset_IMG = DATA_ROOT / 'Dataset_IMG' # generated by pipeline1
    Dataset_ABAW10th_processed = DATA_ROOT / 'Dataset_ABAW_processed' # generated by pipeline2

    ABAW_FACE09_ROOT = Dataset_ABAW10th_processed / 'ABAW_face09'   # generated by pipeline2
    ABAW_FACE12_ROOT = Dataset_ABAW10th_processed / 'ABAW_face12'   # generated by pipeline2
    ABAW_FACE15_ROOT = Dataset_ABAW10th_processed / 'ABAW_face15'   # generated by pipeline2


    # ================= metadata =====================
    RUN_ROOT = PROJECT_ROOT / "runs"

    METADATA_ROOT = PROJECT_ROOT / "metadata"

    EXPR_VIDEO_INDEX_CSV = METADATA_ROOT / "expr_video_index.csv"   # generated by pipeline2.step1
    EXPR_5FOLD = METADATA_ROOT / 'expr_cv5_txtid_randomsearch' / "expr_cv5_folds.csv"
    # ================= pipelines =====================
    PIPELINE_1_ROOT = PROJECT_ROOT / "pipeline1_create"
    PIPELINE_2_ROOT = PROJECT_ROOT / "pipeline2_face_extract"
    PIPELINE_3_ROOT = PROJECT_ROOT / "pipeline3_feature_extract"

    PIPELINE_5_ROOT = PROJECT_ROOT / 'pipeline5_face_point_extract'

    INSIGHTFACE_ROOT = PIPELINE_2_ROOT / "insightface"  # generated by pipeline2.step2
    VIT_WEIGHTS_ROOT = PIPELINE_3_ROOT / 'VIT_weights'  # generated by pipeline3.step1
    LIB_ROOT = PIPELINE_3_ROOT / 'lib' # dinov2 from https://github.com/facebookresearch/dinov2

    # ================= feature =====================
    VIS_FEATURE_ROOT = DATA_ROOT / 'VIS_feature'    # generated by pipeline3.step2
    """
    PT:pretrained
    FT1:normal finetuned
    FT2:auged finetuned
    FT3:auged finetuned without Padding Augmentation
    """
    OFFIMG_V_DINOV2_PT = VIS_FEATURE_ROOT / 'offIMG_v_dinov2_pt'
    OFFIMG_V_DINOV2_FT1 = VIS_FEATURE_ROOT / 'offIMG_v_dinov2_ft1'
    OFFIMG_V_DINOV2_FT2 = VIS_FEATURE_ROOT / 'offIMG_v_dinov2_ft2'
    OFFIMG_V_DINOV2_FT3 = VIS_FEATURE_ROOT / "offIMG_v_dinov2_ft3"

    FACE09_V_DINOV2_PT = VIS_FEATURE_ROOT / 'face09_v_dinov2_pt'
    FACE09_V_DINOV2_FT1 = VIS_FEATURE_ROOT / 'face09_v_dinov2_ft1'
    FACE09_V_DINOV2_FT2 = VIS_FEATURE_ROOT / 'face09_v_dinov2_ft2'
    FACE09_V_DINOV2_FT3 = VIS_FEATURE_ROOT / "face09_v_dinov2_ft3"

    FACE12_V_DINOV2_PT = VIS_FEATURE_ROOT / 'face12_v_dinov2_pt'
    FACE12_V_DINOV2_FT1 = VIS_FEATURE_ROOT / 'face12_v_dinov2_ft1'
    FACE12_V_DINOV2_FT2 = VIS_FEATURE_ROOT / 'face12_v_dinov2_ft2'
    FACE12_V_DINOV2_FT3 = VIS_FEATURE_ROOT / "face12_v_dinov2_ft3"

    FACE15_V_DINOV2_PT = VIS_FEATURE_ROOT / 'face15_v_dinov2_pt'
    FACE15_V_DINOV2_FT1 = VIS_FEATURE_ROOT / 'face15_v_dinov2_ft1'
    FACE15_V_DINOV2_FT2 = VIS_FEATURE_ROOT / 'face15_v_dinov2_ft2'
    FACE15_V_DINOV2_FT3 = VIS_FEATURE_ROOT / "face15_v_dinov2_ft3"


    OFFAUDIO_WAV2VEC2_PT = DATA_ROOT / 'AUD_feature' / 'wav2vec2_fairseq_large_lv60k_asr_ls960_pt'
    OFFAUDIO_WAV2VEC2_PT2 = DATA_ROOT / 'AUD_feature' / 'ABAW10_audio_wavs_16k'

    OFFAUDIO_WAV2VEC2_PT_aligned_nearest = DATA_ROOT / 'AUD_feature' / 'aligned_to_video_frames_nearest'
    OFFAUDIO_WAV2VEC2_PT_aligned_window25 = DATA_ROOT / 'AUD_feature' / 'aligned_to_video_frames_win025'
    OFFAUDIO_WAV2VEC2_PT_aligned_window50 = DATA_ROOT / 'AUD_feature' / 'aligned_to_video_frames_win050'
    OFFAUDIO_WAV2VEC2_PT_aligned_window75 = DATA_ROOT / 'AUD_feature' / 'aligned_to_video_frames_win075'

    IMGSET_V_DINOV2_FT2 = VIS_FEATURE_ROOT / 'IMGset_v_dinov2_ft2'

    # ====================
    # ======test SET======
    # ====================
    ABAW_FACE09_ROOT_TEST = Dataset_ABAW10th_processed / 'ABAW_face09_test'
    ABAW_FACE12_ROOT_TEST = Dataset_ABAW10th_processed / 'ABAW_face12_test'
    ABAW_FACE15_ROOT_TEST = Dataset_ABAW10th_processed / 'ABAW_face15_test'
    FACE09_V_DINOV2_FT2_TEST = VIS_FEATURE_ROOT / 'face09_v_dinov2_ft2_test'
    FACE12_V_DINOV2_FT2_TEST = VIS_FEATURE_ROOT / 'face12_v_dinov2_ft2_test'
    FACE15_V_DINOV2_FT2_TEST = VIS_FEATURE_ROOT / 'face15_v_dinov2_ft2_test'

    OFFAUDIO_WAV2VEC2_PT_TEST = DATA_ROOT / 'AUD_feature' / 'wav2vec2_fairseq_large_lv60k_asr_ls960_pt_test'
    OFFAUDIO_WAV2VEC2_PT2_TEST = DATA_ROOT / 'AUD_feature' / 'ABAW10_audio_wavs_16k_test'
    OFFAUDIO_WAV2VEC2_PT_aligned_window50_TEST = DATA_ROOT / 'AUD_feature' / 'aligned_to_video_frames_win050_test'

    METADATA_ROOT_TEST = PROJECT_ROOT / 'pipeline_TEST' / 'metadata_TESTSET'
    test_ids_txt  = METADATA_ROOT_TEST / 'Expression_Recognition_Challenge_test_set_release.txt'
    frame_ids_txt = METADATA_ROOT_TEST / 'ABAW_Expr_test_set_sample.txt'
    EXPR_VIDEO_INDEX_CSV_TEST = METADATA_ROOT_TEST / 'expr_test_video_index.csv'
    EXPR_VIDEO_META_CSV_TEST = METADATA_ROOT_TEST / 'expr_test_video_meta.csv'

    PIPELINE_TEST = PROJECT_ROOT / 'pipeline_TEST'
    testIMGs = PIPELINE_TEST / 'testIMGs'
# 检查所有路径完整性
import inspect

def verify_paths(path_class):
    print("==== Verifying PATH entries ====\n")
    total = 0
    missing = 0
    for name, value in inspect.getmembers(path_class):
        if isinstance(value, Path):
            total += 1
            if value.exists():
                print(f"[OK]       {name:<25} -> {value}")
            else:
                print(f"[MISSING]  {name:<25} -> {value}")
                missing += 1

    print("\n==== Summary ====")
    print(f"Total Path entries: {total}")
    print(f"Missing paths     : {missing}")
    print(f"Valid paths       : {total - missing}")


if __name__ == "__main__":
    verify_paths(PATH)